### ISSUE TITLE
NotFound on Builder::serve

### ISSUE THREAD

**Issue by Alch-Emi** [panicbit/northstar#1]
Hello!  I'm having some difficulty running the server.  The error appeared in my original code, but it seems to happen in the example too.  I've put some sample code that produces it below, heavily based on the example code.

```rust
use anyhow::*;
use futures::{future::BoxFuture, FutureExt};
use northstar::{Server, Request, Response, GEMINI_PORT};

#[tokio::main]
async fn main() {
    let result = Server::bind(("localhost", GEMINI_PORT))
        .serve(handle_request)
        .await;

    if let Err(e) = result {
        for e in e.chain() {
            println!("{:?}", e);
        }
    }
}

fn handle_request(request: Request) -> BoxFuture<'static, Result<Response>> {
    async move {
        let path = request.path_segments();
        let response = northstar::util::serve_dir("public", &path).await?;

        Ok(response)
    }
    .boxed()
}
```

And the output is:

```
Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

Which also renders as 

```
Error: No such file or directory (os error 2)
```

when the actual example program is run.  I very quickly peeked through the source code, but I don't really know where it's coming from.  It might be worth noting that the `handle_request` method is never run.

Any help is appreciated.  I'm running `0.1.0` off of crates.io.

**Comment by panicbit** [comment]
Sorry for this terrible error message. I think you are missing the tls cert and key. Check the readme for how to create them.

**Comment by Alch-Emi** [comment]
Aa I had missed that!  Thank you!
