### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by aThorp96** [panicbit/northstar#41]
Hello,

This library looks really awesome and I would like to use this library in a server I'm considering writing, but I would like to know what the intended license is, and if one will be added. Without a license the code is currently All Rights Reserved which limits the license I can chose and potentially the legality of using the library in general. 

If you're unsure which license, if any, you want to use with this library I've found this article to be very helpful: 
https://man.sr.ht/license.md

Thank you,

Andrew

**Comment by panicbit** [comment]
https://github.com/panicbit/northstar/blob/75eb58e0c141167d924e6c876cf4682470d92e91/Cargo.toml#L6

I can however add a `LICENSE` file as well.

**Comment by panicbit** [comment]
I've added license files now.
[MIT](https://github.com/panicbit/northstar/blob/98d09c2a13b57ab03c1026d8a48a74e8d3238bce/LICENSE-MIT)
[Apache 2.0](https://github.com/panicbit/northstar/blob/98d09c2a13b57ab03c1026d8a48a74e8d3238bce/LICENSE-APACHE)
